import { cp, mkdir, rm, copyFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
const root=process.cwd(), dist=path.join(root,'dist');
await rm(dist,{recursive:true,force:true}); await mkdir(dist,{recursive:true});
await copyFile(path.join(root,'index.html'),path.join(dist,'index.html'));
await cp(path.join(root,'src'),path.join(dist,'src'),{recursive:true});
await cp(path.join(root,'public'),dist,{recursive:true});
for(const f of ['.nojekyll']) if(existsSync(path.join(root,f))) await copyFile(path.join(root,f),path.join(dist,f));
console.log('[OK] Static build created:',dist);
